services:
    korva-vitrine:
        build:
            context: .
            dockerfile: Dockerfile
            target: production
        env_file:
            - .env
        ports:
            - "8085:3000"
        volumes:
            - .:/app
        restart: unless-stopped
