name: Korva CI/CD

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

jobs:
  security-scan:
    name: Code Analysis, Vulnerability Scan & Leaks Detection
    runs-on: self-hosted
    permissions:
        contents: read
        pull-requests: read
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0
      - name: Gitleaks
        uses: gitleaks/gitleaks-action@e0c47f4f8be36e29cdc102c57e68cb5cbf0e8d1e
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995
        with:
          scannerVersion: 6.2.0.4584
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:
    name: Build the project
    runs-on: ubuntu-24.04
    needs: security-scan
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Configure Docker Buildx
        uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069

      - name: Check if the tests pass
        run: docker compose run --rm korva-vitrine npm test --if-present

      - name: Build the docker image
        uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc
        with:
          load: true
          tags: image_website:${{ github.sha }}

      - name: Export to .tar file
        run: docker save image_website:${{ github.sha }} -o /tmp/image_website.tar

      - name: Upload the Docker image into artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: docker-image
          path: /tmp/image_website.tar
          retention-days: 2
  
  image-scan:
    name: Scan the Docker image to check vulnerabilities
    runs-on: ubuntu-24.04
    needs: build
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout the code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
           persist-credentials: false
      - name: Download the Docker image artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: docker-image
          path: /tmp

      - name: Load Docker image from tar
        run: docker load -i /tmp/image_website.tar

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
        with:
          image-ref: image_website:${{ github.sha }}
          format: 'sarif'
          output: 'trivy-report.sarif'
          severity: 'CRITICAL, HIGH'
          exit-code : '0'
          ignore-unfixed: true
        
      - name: Upload the Trivy report as an artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: trivy-vulnerability-report
          path: trivy-report.sarif
          retention-days: 2
      
  deploy:
    name: Deploy the project
    runs-on: self-hosted
    needs: image-scan
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Download the Docker image artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: docker-image
          path: /tmp

      - name: Load Docker image
        run: docker load -i /tmp/image_website.tar

      - name: Start Docker Containers
        run: docker compose up -d

      - name: Get the local IP address of the runner
        id: local_ip
        run: |
          RUNNER_IP=$(hostname -I | awk '{print $1}')
          echo "IP local address : $RUNNER_IP"
          echo "ip=$RUNNER_IP" >> "$GITHUB_OUTPUT"

      - name: Validate access via IP and port
        run: |
          sleep 10
          echo "Website available at : http://${{ steps.local_ip.outputs.ip }}:8085"
          curl -v http://${{ steps.local_ip.outputs.ip }}:8085

      - name: Docker Clean Up
        run: docker image prune -f

  dast_scan:
    name: Dynamic Analysis with OWASP ZAP
    runs-on: ubuntu-24.04
    needs: deploy
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Scan DAST with OWASP ZAP
        uses: zaproxy/action-full-scan@3c58388149901b9a03b7718852c5ba889646c27c
        with:
          target: 'http://172.20.20.23:8085'
          cmd_options: '-a'
          fail_action: false
          artifact_name: 'zap-raw-html-report'

      - name: Install wkhtmltopdf
        run: |
          sudo apt-get update
          sudo apt-get install -y wkhtmltopdf

      - name: Convert ZAP report into PDF
        run: |
          wkhtmltopdf --enable-local-file-access report_html.html zap-vulnerability-report.pdf

      - name: Publish the report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: zap-vulnerability-report-pdf
          path: zap-vulnerability-report.pdf
          retention-days: 2

  send_email:
    name: Send the reports by email
    runs-on: ubuntu-24.04
    needs: [image-scan, dast_scan]
    permissions:
      contents: read
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Download the Trivy report
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: trivy-vulnerability-report
          path: .

      - name: Download the ZAP report
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: zap-vulnerability-report-pdf
          path: .

      - name: Send email with reports
        uses: dawidd6/action-send-mail@67ce3558d613188179559c61d3565140cf389968
        with:
          server_address: ${{ secrets.MAIL_SERVER }}
          server_port: ${{ secrets.MAIL_PORT }}
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Security Reports regarding the project Korva"
          to: ${{ secrets.MAIL_TO }}
          from: KORVA Deployment Team
          body: |
            Hello Team,

            Please find attached the latest security reports for the Korva project.

            1. Trivy Vulnerability Report (SARIF format)
            2. OWASP ZAP Dynamic Analysis Report (PDF format)

            Best regards,
            Kael Avande,
            KORVA Deployment Team
          attachments: trivy-report.sarif, zap-vulnerability-report.pdf

            





